config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
  }

  root 'home#index'
  
  get 'member/:id', to: 'members#show', as: "member"
  
  get 'edit_description', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: "update_member_description"

  get 'edit_personal_details', to: 'members#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'members#update_personal_details', as: "update_member_personal_details"
  get "member-connections/:id", to: "members#connections", as: "member_connections"

  resources :work_experiences
  resources :connections
end

app/models/connection.rb
class Connection < ApplicationRecord
  CONNECTION_STATUSES = %w(pending accepted rejected deleted)
  belongs_to :user
  belongs_to :requested, foreign_key: :connected_user_id, class_name: "User"
  belongs_to :received, foreign_key: :user_id, class_name: "User"

  validates :connected_user_id, presence: true
  validates :status, presence: true, inclusion: { in: CONNECTION_STATUSES }

  def status_btn
    case status
    when "accepted"
      "btn btn-success"
    when "rejected"
      "btn btn-danger"
    else
      "btn btn-primary"
    end
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

  def index
    @requested_connections = Connection.includes(:requested).where(user_id: current_user.id)
    @received_connections = Connection.includes(:received).where(connected_user_id: current_user.id)
  end

  def create
    @connection = current_user.connections.new(connection_params)
    @connector = User.find(connection_params[:connected_user_id])
      if @connection.save
        render_turbo_stream(
          'replace',
          "user-connection-status",
          'connections/create',
          { connector: @connector }
        )
      end
  end

  def update
    @connection = Connection.find(params[:id])
      ActiveRecord::Base.transaction do 
        if @connection.update(connection_params)
          if @connection.status == "accepted"
            receiver = @connection.received
            receiver.connected_user_ids << @connection.requested.id
            receiver.save

            requester = @connection.requested
            requester.connected_user_ids << @connection.received.id
            requester.save
          end
        end
      end
      render_turbo_stream(
      'replace',
      "connection-status-#{@connection.id}",
      'connections/update',
      { connection: @connection }
    )
  end

  private

  def connection_params
    params.require(:connection).permit(:user_id, :connected_user_id, :status)
  end
end

app/views/connections/_create.html.erb
<button type="button" class="btn btn-primary">Pending</button><br>

<small class="text-muted">Your connection request has been send , but it is in pending state. You will get connected once <span class="fw-bold"><%= connector.name %></span> will accept your connnection request</small><br>

app/views/connections/_update.html.erb
<div class="d-grid">
  <% if connection.status == "accepted" %>
    <%= link_to connection.status.titleize, "javascript:void(0)", class: "btn btn-success mt-2" %>
    <% elsif connection.status == "rejected" %>
      <%= link_to connection.status.titleize, "javascript:void(0)", class: "btn btn-danger mt-2" %>
    <% else %>
      <%= link_to connection.status.titleize, "javascript:void(0)", class: "btn btn-primary mt-2" %>
    <% end %>
</div>

app/views/connections/index.html.erb
<div class="col-lg-10 mx-auto mt-4">
  <% if @requested_connections.present? %>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Requested Connections</h3>
      </div>
      <div class="card-body text-center">
        <div class="row">
          <% @requested_connections.each do |connection| %>
            <div class="col-lg-3">
              <div class="card mt-2">
                <div class="card-body">
                  <%= image_tag 'images.png', class: "img-fluid mb-1" %>
                  <div style="min-height: 100px" >
                    <%= link_to member_path(connection.requested), class: "text-decoration-none text-primary", target: "_blank" do %>
                      <p class="lead fw-bold"><%= connection.requested.name %></p>
                    <% end %>
                    <small class="text-muted"><%= connection.requested.profile_title %></small><br>
                  </div>
                  <div class="d-grid">
                    <%= link_to connection.status.titleize, "javascript:void(0)", class: "#{connection.status_btn} mt-2" %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <% if @received_connections.present? %>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Received Connections</h3>
      </div>
      <div class="card-body text-center">
        <div class="row">
          <% @received_connections.each do |connection| %>
            <div class="col-lg-3">
              <div class="card mt-2">
                <div class="card-body">
                  <%= image_tag 'images.png', class: "img-fluid mb-1" %>
                  <div style="min-height: 100px">
                    <%= link_to member_path(connection.received), class: "text-decoration-none text-primary", target: "_blank" do %>
                      <p class="lead fw-bold"><%= connection.received.name %></p>
                    <% end %>
                    <small class="text-muted"><%= connection.received.profile_title %></small><br>
                  </div>
                  <div id="connection-status-<%= connection.id %>">
                    <% if ["accepted", "rejected"].include?(connection.status) %>
                      <div class="d-grid">
                        <%= link_to connection.status.titleize, "javascript:void(0)", class: "#{connection.status_btn} mt-2" %>
                      </div>
                    <% else %> 
                       <%= link_to "Accept", connection_path(connection), class: "btn btn-success mt-2", data: { controller: "update-connection-status", turbo_method: :patch } %>
                       <%= link_to "Reject", connection_path(connection), class: "btn btn-danger mt-2", data: { controller: "update-connection-status", turbo_method: :patch } %>
                    <% end %> 
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>