config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
  }

  root 'home#index'
  
  get 'member/:id', to: 'members#show', as: "member"
  
  get 'edit_description', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: "update_member_description"

  get 'edit_personal_details', to: 'members#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'members#update_personal_details', as: "update_member_personal_details"
  get "member-connections/:id", to: "members#connections", as: "member_connections"

  resources :work_experiences
  resources :connections
end

app/models/work_experience.rb
class WorkExperience < ApplicationRecord

  EMPLOYMENT_TYPE = ["Full-Time", "Part-Time", "Self-employeed", "Freelance", "Trainee", "Intership"]
  LOCATION_TYPE = ["Onsite", "Hybrid", "Remote"]

  belongs_to :user

  validates :company, :start_date, :job_title, :location, presence: true
  validates :employment_type, presence: true, inclusion: { in: EMPLOYMENT_TYPE, message: "not a valid EMPLOYMENT_TYPE" }
  validates :location_type, presence: true, inclusion: { in: LOCATION_TYPE, message: "not a valid LOCATION_TYPE" }

  validate :work_experience_last_date
  validate :presence_of_end_date
  validate :end_date_greater_than_start_date, if: :currently_not_working_here?
  
  def work_experience_last_date
    if end_date.present? && currently_working_here
      errors.add(:end_date, "Must be blank if you are currently working in this company")
    end
  end      

  def presence_of_end_date
    if end_date.nil? && !currently_working_here
      errors.add(:end_date, "Must be present If you are not Working in this company")
    end
  end 

  def currently_not_working_here? 
    !currently_working_here
  end     

  def end_date_greater_than_start_date
    return if end_date.nil?

    if end_date < start_date
      errors.add(:end_date, "Must be greater than start date")
    end
  end

  def company_with_employment_type
    "#{company} (#{employment_type})".strip
  end

  def job_location
    "#{location} (#{location_type})"
  end

  def job_duration
    months = if end_date.present?
                fetch_months(end_date)
             else
                fetch_months(Date.today)
             end

    result = months.divmod(12)

    duration = "#{result.first} #{result.first > 1 ? "years" : "year"} #{result.last} #{result.last > 1 ? "months" : "month" }"

    if currently_working_here
      "#{start_date.strftime("%b %Y")} - Present (#{duration})"
    else
      "#{start_date.strftime("%b %Y")} - #{end_date.strftime("%b %Y")} (#{duration})"
    end
  end

  def fetch_months(last_date)
    ((last_date.year - start_date.year) * 12 + last_date.month - start_date.month - (last_date.day >= start_date.day ? 0 : 1)).round
  end

end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  before_action :set_work_experience, only: %i[edit update destroy]

  def new
    @work_experience = current_user.work_experiences.new
  end

  def create
    @work_experience = current_user.work_experiences.new(work_experience_params)
      if @work_experience.save
        render_turbo_stream(
          'append',
          "work_experience_items",
          'work_experiences/work_experience',
          { work_experience: @work_experience }
        )
      else
        render_turbo_stream(
          'replace',
          "remote_modal",
          'shared/turbo_modal',
          { 
            form_partial: "work_experiences/form",
            modal_title: "Add new work experience"
          }
        )
      end
  end

  def edit
  end

  def update
    if @work_experience.update(work_experience_params)
      render_turbo_stream(
        'replace',
        "work_experience_item_#{@work_experience.id}",
        'work_experiences/work_experience',
        { work_experience: @work_experience }
      )
    else
      render_turbo_stream(
        'replace',
        "remote_modal",
        'shared/turbo_modal',
        {
          form_partial: "work_experiences/form",
          modal_title: "Edit work experience"
        }
      )
    end
  end

  def destroy
    @work_experience.destroy
    render_turbo_stream(
        'remove',
        "work_experience_item_#{@work_experience.id}"
      )
  end

  private

  def set_work_experience
    @work_experience = current_user.work_experiences.find(params[:id])
  end

  def work_experience_params
    params.require(:work_experience).permit(:start_date, :end_date, :currently_working_here, :company, :location, :location_type, :employment_type, :description, :job_title, :user_id)
  end
end

app/views/work_experiences/_form.html.erb
<%= form_with model: @work_experience do |form| %>
  <div class="modal-body">
    <div class="row">
      <% if @work_experience.errors.any? %>
        <div class="error-area" style="color:red;">
          <h3><%= pluralize(@work_experience.errors.count, "error") %> prohibited your work experience from being saved.</h3>
          <ul>
            <% @work_experience.errors.each do  |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-lg-12">
        <div class="form-group">
          <label class="mb-2 mt-3">Title <span class="text-danger">*</span></label>
          <%= form.text_field :job_title, class: "form-control" %>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">Company <span class="text-danger">*</span></label>
          <%= form.text_field :company, class: "form-control" %>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">Employement Type <span class="text-danger">*</span></label>
          <%= form.select :employment_type, options_for_select(WorkExperience:: EMPLOYMENT_TYPE,  selected: form.object.employment_type), {prompt: "Select employment type"}, class: "form-select" %>
        </div> 

        <div class="form-group">
          <label class="mb-2 mt-3">Location <span class="text-danger">*</span></label>
          <%= form.text_field :location, class: "form-control" %>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">Location Type <span class="text-danger">*</span></label>
          <%= form.select :location_type, options_for_select(WorkExperience:: LOCATION_TYPE,  selected: form.object.location_type), {prompt: "Select location type"}, class: "form-select" %>
        </div>

        <!-- ------------Date Field--------- -->
        <div class="form-group row">
          <div class="col-lg-12 mt-3">
            <div class="form-check form-switch">
              <%= form.check_box :currently_working_here, class: "form-check-input", role: "switch", data: { controller: "disable-end-date" } %>
              <label for="work_experience_currently_working_here" class="form-check-label">I am currently working here</label>
            </div>
          </div>
          <div class="col-lg-6">
            <label class="mb-2 mt-3">
              Start Date <span class="text-danger">*</span>
            </label>
            <%= form.date_field :start_date, class: "form-control" %>
          </div>
          <div class="col-lg-6">
            <label class="mb-2 mt-3">
              End Date <span class="text-danger">*</span>
            </label>
            <%= form.date_field :end_date, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">Description</label>
          <%= form.text_area :description, class: "form-control", rows: 5 %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit "Save Changes", class: "btn btn-primary", data: { action: "click->bs-modal#submitEnd" } %>
  </div>
<% end %>

app/views/work_experiences/_work_experience.html.erb
<li class="list-group-item" id="work_experience_item_<%= work_experience.id %>" >
  <div class="row">
    <div class="col-lg-9">
      <div class="d-flex justify-content-start">
        <p class="fw-bold"><%= work_experience.job_title %></p>
      </div>
    </div>
    <div class="col-lg-3">
      <div class="d-flex justify-content-end gap-2">
        <%= link_to edit_work_experience_path(work_experience), data: { controller: "bs-modal-form" } do %>
          <i class="bi bi-pencil-fill"></i>
        <% end %>
        <%= link_to work_experience_path(work_experience), data: { turbo_method: :delete, turbo_confirm: "Are You sure you want to delete this experience" } do %>
          <i class="bi bi-trash3-fill text-danger "></i>
        <% end %>
      </div>
    </div>
  </div>
  <small><%= work_experience.company_with_employment_type %></small><br>
  <small><%= work_experience.job_location %></small><br>
  <small><%= work_experience.job_duration %></small><br>
</li>

app/views/work_experiences/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: "Edit work experience", form_partial: "work_experiences/form" %>
<% end %>

app/views/work_experiences/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: "Add new work experience", form_partial: "work_experiences/form" %>
<% end %>