config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
  }

  root 'home#index'
  
  get 'member/:id', to: 'members#show', as: "member"
  
  get 'edit_description', to: 'members#edit_description', as: 'edit_member_description'
  patch 'update_description', to: 'members#update_description', as: "update_member_description"

  get 'edit_personal_details', to: 'members#edit_personal_details', as: 'edit_member_personal_details'
  patch 'update_personal_details', to: 'members#update_personal_details', as: "update_member_personal_details"
  get "member-connections/:id", to: "members#connections", as: "member_connections"

  resources :work_experiences
  resources :connections
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @connections = Connection.where('user_id = ? OR connected_user_id = ?', params[:id], params[:id]).where(status: "accepted")
    @mutual_connections = current_user.mutually_connected_ids(@user)

  end

  def edit_description;
  end

  def update_description
      if current_user.update(about: params[:user][:about])
        render_turbo_stream(
          "replace",
          "member-description",
          'members/member_description',
          { user: current_user }
        )
      end
  end

  def edit_personal_details
  end

  def update_personal_details
      if current_user.update(user_personal_info_params)
        render_turbo_stream(
          'replace',
          'member-personal-details',
          'members/member_personal_details',
          { user: current_user }
        )
      end
  end

    def connections
    @user = User.find(params[:id])
    total_users = if params[:mutual_connections].present?
                          mutually_connected_ids = current_user.mutually_connected_ids(@user)
                          User.where(id: mutually_connected_ids)
                        else
                          User.where(id: @user.connected_user_ids)
                        end
    @connected_users = total_users.page(params[:page]).per(10)
    @total_connections = total_users.count
  end


  private

  def user_personal_info_params
    params.require(:user).permit(:first_name, :last_name, :city, :state, :country, :pincode, :profile_title)
  end


end

app/views/members/_description_modal.html.erb
<%= form_with model: current_user, url: update_member_description_path, method: :patch do |form| %>
  <div class="modal-body">
    <div class="row">
      <div class="col-lg-12">
        <div class="form-group">
          <label for="" class="mb-3">Edit your description here. Try to keep it simple and to the point so the can findvaluable details of yours.</label>
          <%= form.text_area :about, value: current_user.about, class: "form-control", rows: 15%>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= form.submit "Save Changes", class: "btn btn-primary", data: { action: "click->bs-modal#submitEnd" } %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/members/_member_description.html.erb
<p class="lead" id="member-description"><%= user.about %></p>

app/views/members/_member_personal_details.html.erb
<div class="card mb-4" id="member-personal-details">
  <div class="row">
    <div class="col-lg-4">
      <%= image_tag "images.png", class: "img-fluid" %>
    </div>
    <div class="col-lg-8">
      <div class="card-body">
        <div class="row">
          <div class="col-lg-10">
            <div class="d-flex justify-content-start">
              <h3 class="fw-bold"><%= user.name %></h3>
            </div>
          </div>
          <% if user == current_user %>
            <div class="col-lg-2">
              <div class="d-flex justify-content-end">
                <%= link_to edit_member_personal_details_path, class: "edit-profile", data: { controller: "bs-modal-form" } do %>
                  <i class="bi bi-pencil-fill"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
        <p class="lead"><%= user.profile_title %></p>
        <p class="lead text-primary"><%= user.address %></p>

        <div id="user-connection-status">
          <% if current_user.check_if_already_connected?(user) %>
            <%= link_to "Connect", connections_path, class: "btn btn-primary", data: { controller: "connections",
              turbo_method: :post,
              connections_target: "connection",
              requester_id: current_user.id,
              connected_id: user.id } %>
          <% elsif get_connection_status(user) == "pending" %>
            <%= render "connections/create", connector: user %>
          <% elsif get_connection_status(user) == "accepted" %>
            <button type="button" class="btn btn-success">Connected</button>
          <% elsif get_connection_status(user) == "rejected" %>
            <button type="button" class="btn btn-danger">Rejected</button>
          <% end %>
        </div>
        <% if @connections.present? %>
          <div id="connection-count">
            <%=link_to pluralize(@connections.count, 'connection'), member_connections_path(user), class: "text-decoration-none" %>
          </div>
        <% end %> 

        <% if current_user != @user && @mutual_connections.present? && @mutual_connections.count > 0 %> 
          <div id="mutual-connection-count">
            <%=link_to pluralize(@mutual_connections.count, 'mutual connection'), member_connections_path(user, mutual_connections: true), class: "text-decoration-none" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/members/_personal_info_modal.html.erb
<%= form_with model: current_user, url: update_member_personal_details_path, method: :patch do |form| %>
  <div class="modal-body">
    <div class="row">
      <div class="col-lg-12">
        <div class="form-group row">
          <div class="col-lg-6">
            <%= form.label :first_name, class: "mb-3 mt-3" %>
            <%= form.text_field :first_name, class: "form-control", value: current_user.first_name %>
          </div>
          <div class="col-lg-6">
            <%= form.label :last_name, class: "mb-3 mt-3" %>
            <%= form.text_field :last_name, class: "form-control", value: current_user.last_name %>
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="form-group row">
          <div class="col-lg-6">
            <%= form.label :city, class: "mb-3 mt-3" %>
            <%= form.text_field :city, class: "form-control", value: current_user.city %>
          </div>
          <div class="col-lg-6">
            <%= form.label :state, class: "mb-3 mt-3" %>
            <%= form.text_field :state, class: "form-control", value: current_user.state %>
          </div>
          <div class="col-lg-6">
            <%= form.label :country, class: "mb-3 mt-3" %>
            <%= form.text_field :country, class: "form-control", value: current_user.country %>
          </div>
          <div class="col-lg-6">
            <%= form.label :pincode, class: "mb-3 mt-3" %>
            <%= form.text_field :pincode, class: "form-control", value: current_user.pincode %>
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="form-group">
          <%= form.label :profile_title, class: "mb-3 mt-3" %>
          <%= form.text_field :profile_title, class: "form-control", value: current_user.profile_title %>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit "Save Changes", class: "btn btn-primary", data: { action: "click->bs-modal#submitEnd" } %>
  </div>
<% end %>

app/views/members/connections.html.erb
<div class="col-lg-10 mx-auto mt-5">
  <div class="row">
    <div class="col-lg-8">
      <p class="lead fw-bold">About <%= pluralize(@total_connections, "result") %></p>
      <% if @connected_users.present? %>
        <% @connected_users.each do |user| %>
          <div class="card mb-2">
            <div class="row">
              <div class="col-lg-2">
                <%= image_tag "images.png", class: "img-fluid rounded-1 m-1" %>
              </div>
              <div class="col-lg-10">
                <div class="card-body">
                  <%= link_to member_path(user), class: "text-decoration-none", target: "_blank" do %>
                    <h4 style="margin-bottom: -2px;"><%= user.name %></h4>
                  <% end %>

                  <% if current_user != @user %>
                    <% mutual_connection_count = current_user.mutually_connected_ids(@user).count %>
                  <% else %>
                    <% mutual_connection_count = current_user.mutually_connected_ids(user).count %>
                  <% end %>
                  <% if mutual_connection_count > 0 %>
                    <%= link_to member_connections_path(user, mutual_connections: true), class: "text-decoration-none", target: "_blank" do %>
                      <small class="text-primary"><%= pluralize(mutual_connection_count, "mutual connection") %></small><br>
                    <% end %>
                  <% end %>  
                  <small class="text-muted"><%= user.profile_title %></small><br>
                  <small class="text-muted"><%= user.address %></small><br>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <%= paginate @connected_users %>
    </div>
  </div>
</div>

app/views/members/edit_description.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render "shared/turbo_modal", modal_title: "Edit Your Description", form_partial: "members/description_modal" %>
<% end %>

app/views/members/edit_personal_details.turbo_stream.erb
<%= turbo_stream.replace 'remote_modal' do %>
  <%= render  'shared/turbo_modal', modal_title: "Edit Your Personal Information", form_partial: "members/personal_info_modal" %>
<% end %>

app/views/members/show.html.erb
<div class="col-lg-10 mx-auto mt-4">
  <%= render "member_personal_details", user: @user %>
  
  <div class="card mb-4">
    <div class="card-body"> 
      <div class="row">
        <div class="col-lg-6">
          <div class="d-flex justify-content-start">
            <h3>About</h3>
          </div>
        </div>
        <% if @user == current_user %>
          <div class="col-lg-6">
            <div class="d-flex justify-content-end">
              <%= link_to edit_member_description_path, class: "edit-about", data: { controller: "bs-modal-form" } do %>
                <i class="bi bi-pencil-fill"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <%= render "member_description", user: @user %>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-body">
      <% if @user == current_user %>
        <div class="row">
          <div class="col-lg-4">
            <div class="d-flex justify-content-start">
              <h3>Work Experiences</h3>
            </div>
          </div>

          <div class="col-lg-4">
            <div class="d-flex justify-content-end">
              <%= link_to new_work_experience_path, class: "text-decoration-none  ", data: { controller: "bs-modal-form" } do %>
                <i class="bi bi-plus"></i>
                <span class="ms-1">Add Experience</span>
              <% end %>
            </div>
          </div>

          <% if @user.work_experiences.present? %>
            <div class="col-lg-4 ">
              <div class="d-flex justify-content-end">
                <%= link_to "javascript:void(0)", class: "text-decoration-none" do %>
                  <i class="bi bi-pencil-fill"></i>
                  <span class="ms-1">Edit Experiences</span>
                <% end %>
              </div>
          </div>
          <% end %>
        </div>
      <% end %>

      <% if @user.work_experiences.present? %>
        <ul class="list-group" id="work_experience_items">
          <% @user.work_experiences.each do |work_experience| %>
            <%= render "work_experiences/work_experience", work_experience: work_experience %>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>